# 未踏ジュニア - 提案書を準備しよう
# https://jr.mitou.org/applications/

# 応募者向け提案書サンプル (最新順)
# https://jr.mitou.org/applications/#sample
- project_id: jellyfish_alert
  type: sample
- project_id: tactica_note
  type: sample
- project_id: niwangojs
  type: sample
- project_id: mer
  type: sample
- project_id: noxicel
  type: sample
- project_id: flight_fit_vr
  type: sample
- project_id: visible
  type: sample
- project_id: det_exploit
  type: sample
- project_id: amoyo
  type: sample
- project_id: abecobe
  type: sample

# メンターによる提案書のコツ
# https://jr.mitou.org/applications/#tips
- mentor_id: yu_ukai
  title: なぜ「未踏」は多くの若い世代に知られるべきなのか
  link: https://medium.com/@ukkaripon/なぜ-未踏-は多くの若い世代に知られるべきなのか-1fb31ac9fda3
  type: tips
- mentor_id: yohei_yasukawa
  title: 多様なメンター、多様な基準
  link: https://speakerdeck.com/yasulab/believe-in-your-passion
  type: tips
- mentor_id: yoshifumi_seki
  title: 未踏ジュニアにおけるよい提案資料の書き方、もしくはアイデアの伝え方と評価について
  link: https://note.com/yoshifumiseki/n/n1e928281d7dc
  type: tips
- mentor_id: ryo_suzuki
  title: 未踏ジュニア、伝わる提案書を作る 5 つのコツ
  link: https://zenn.dev/reputeless/articles/idea-mitoujr
  type: tips
- mentor_id: daiki_teramoto
  title: 提案書のよくある「もったいない」点の紹介
  link: https://note.com/teramotodaiki/n/n148d35899016
  type: tips
- mentor_id: hirokazu_nishio
  title: プロジェクト提案書ってどう書くの？
  link: https://scrapbox.io/nishio/プロジェクト提案書ってどう書くの？
  type: tips

# 採択者の体験談
# （公式インタビュー記事は自動追加のため不要）
# https://jr.mitou.org/applications/#story
- project_id: jellyfish_alert
  title: 未踏ジュニア2024を終えて
  link: https://note.com/sh_o4964/n/n07afe27ab5bc
  type: story
- project_id: stask
  title: 未踏ジュニア振り返り
  link: https://zenn.dev/toshihiro_tange/articles/mitoujr-advent-calendar-2023
  type: story
- project_id: sanitas
  title: 未踏ジュニア振り返り・提案書
  link: https://qiita.com/MasudaHinata/items/b686009b0e741d30cf01
  type: story
- project_id: cybotanic
  title: 採択されるために私が意識したこと/アドバイス
  link: https://note.com/ricksh/n/n5fa51f9142b2
  type: story
- project_id: skimer
  title: スーパークリエータに認定されたりアプリ甲子園で準優勝したりするまで
  link: https://note.com/anharu/n/ne00c1e774a29
  type: story
- project_id: ai_4koma_maker
  title: 未踏ジュニアの振り返り
  link: https://note.com/k1ut_/n/nbc541a9b6dc1
  type: story
- project_id: mark_sdgs
  title: 未踏ジュニアの振り返り
  link: https://note.com/redapple0414/n/nd20c49794b79
  type: story
- project_id: noxicel
  title: 未踏ジュニア振り返り・提案書
  link: https://note.com/alicelavanderdev/n/nb528b1bdbb93
  type: story
- project_id: a9n
  title: 未踏ジュニアに応募しよう
  link: https://horizon2k38.hatenablog.com/entry/2024/06/01/103142
  type: story
- project_id: code_museum
  title: 未踏ジュニアがついに終わったので苦悩と成功の半年間をまとめる
  link: https://zenn.dev/waryu/articles/mitoujr-2023-waryu
  type: story
- project_id: critica
  title: 未踏ジュニア振り返りと、技術力に差があるチーム開発の僕なりの攻略方法
  link: https://note.com/inoue2002/n/nfb57cd6825a4
  type: story
#- project_id: 
#  title: 
#  link: 
#  type: story

# 採択者のメディア掲載
# https://jr.mitou.org/applications/#news
- project_id: draw_code
  title: 中学2年生にしてiPhoneアプリを5本リリース、毎日1アイデアを考える未踏ジュニアスーパークリエータ
  link: https://edtechzine.jp/article/detail/780
  type: news
- project_id: vamboo
  title: '高校生なのにエンジニアインターン!? ほぼ不登校から大学受験もプログラミングで突破した未踏ジュニアスーパークリエータ'
  link: https://edtechzine.jp/article/detail/829
  type: news
- project_id: toubans
  title: 「50センチ革命」の先にあるものとは。未踏ジュニアからLINE BOOT AWARDSグランプリ受賞、SXSW Eduでもピッチをした未踏ジュニアスーパークリエータ
  link: https://edtechzine.jp/article/detail/1976
  type: news
